import { getCardDef, PERSONA_CATALOG, type BaseRoleId, type CardDef, type PersonaId } from "@minus1days/shared";

// Persona portraits are generated by `scripts/generate-assets.mjs` into
// src/assets/cards/personas/<PersonaId>.svg. Vite's `import.meta.glob` resolves the
// whole directory eagerly at build time so any persona id just works, including a
// future 9th/10th persona — no import list to keep in sync by hand.
const personaSvgModules = import.meta.glob<string>("../assets/cards/personas/*.svg", {
  eager: true,
  query: "?url",
  import: "default",
});

const personaAssetMap: Record<string, string> = {};
for (const path in personaSvgModules) {
  const match = path.match(/([^/\\]+)\.svg$/);
  if (match) personaAssetMap[match[1]] = personaSvgModules[path];
}

export function getPersonaPortraitUrl(personaId: PersonaId): string | null {
  return personaAssetMap[personaId] ?? null;
}

/**
 * Looks a persona up by its CARD_CATALOG defId (e.g. "PERSONA_BOB"), for use inside <Card>.
 * PERSONA_CATALOG is keyed by PersonaId (e.g. "BOB") but each entry's own `.id` field is the
 * CardDef id ("PERSONA_BOB") — callers need the PersonaId key too (e.g. to look up portrait
 * assets named after the enum), so it's returned alongside the entry as `personaId`.
 */
export function findPersonaEntryByDefId(defId: string) {
  const found = (Object.entries(PERSONA_CATALOG) as [PersonaId, (typeof PERSONA_CATALOG)[PersonaId]][]).find(
    ([, p]) => p.id === defId
  );
  if (!found) return null;
  const [personaId, entry] = found;
  return { ...entry, personaId };
}

/** getCardDef throws on an unknown id; the UI would rather show "unknown card" than crash. */
export function safeGetCardDef(defId: string): CardDef | null {
  try {
    return getCardDef(defId);
  } catch {
    return null;
  }
}

export function baseRoleDefId(role: BaseRoleId): string {
  return `ROLE_${role}`;
}

const BASE_ROLE_LABELS: Record<string, string> = {
  INSPECTOR: "Thanh tra",
  WHITEHAT: "White Hat",
  BLACKHAT: "Black Hat",
  INSIDER: "Insider",
};

export function baseRoleLabel(role: BaseRoleId): string {
  return BASE_ROLE_LABELS[role] ?? role;
}
