import type { ThemeManifest } from "../types";

// "Terminal Mono" — green-on-black CRT terminal aesthetic: monochrome phosphor green,
// scanlines, sharp corners, monospace everywhere. No glow/glitch flair.
export const terminalMonoTheme: ThemeManifest = {
  id: "terminal-mono",
  name: "Terminal Mono",
  description: "Xanh lá trên nền đen, phong cách màn hình CRT cổ điển.",
  vars: {
    bg: "#050805",
    bgElevated: "#0a0f0a",
    panel: "#0d130d",
    border: "#1e3d1e",
    borderStrong: "#2c5c2c",
    text: "#c8ffc8",
    textMuted: "#5fae5f",
    textDim: "#357035",
    accent: "#39ff5a",
    accentSoft: "#0f2a10",
    danger: "#ff5c3d",
    success: "#39ff5a",
    warning: "#ffd23d",
    gold: "#d8ff3d",
    overlay: "rgba(2, 6, 2, 0.78)",
    shadowColor: "rgba(57, 255, 90, 0.2)",

    fontDisplay: '"VT323", "Consolas", monospace',
    fontBody: '"Share Tech Mono", "Consolas", monospace',
    fontMono: '"Share Tech Mono", "Consolas", monospace',
    letterSpacingWide: "0.12em",

    cardRadius: "2px",
    cardbackBg: "repeating-linear-gradient(0deg, #060a06 0px, #060a06 2px, #0a120a 3px)",
    cardbackLine: "rgba(57, 255, 90, 0.4)",
    cardbackBorder: "#39ff5a",
    frameBg: "#0a0f0a",
    frameBorder: "#2c5c2c",

    typeBaseRole: "#ff5c3d",
    typePersona: "#39ff5a",
    typeAction: "#d8ff3d",
    typeKit: "#3ddaff",
    typeFlag: "#ffd23d",
    typeToken: "#ff9a3d",

    subAttack: "#ff5c3d",
    subDefend: "#3ddaff",
    subDeny: "#ffd23d",
    subLucky: "#39ff5a",
    subPhishing: "#d8ff3d",
    subRansomware: "#ff5c3d",
    subZeroday: "#ff9a3d",
    subBitcoin: "#ffd23d",
    subIncidentResponse: "#39ff5a",
    subKernCoerce: "#ff9a3d",
    subKernBadLuck: "#5fae5f",
    subKernCaesar: "#ffd23d",
    subEnergyDrink: "#39ff5a",
    subUpgrade: "#3ddaff",
    subKernSuperUpgrade: "#ffd23d",

    scanlineOpacity: "1",
    glitchOpacity: "0",
    glowStrength: "0.35",
  },
};
